import type { Metadata } from "next";
import NavigationBar, { NavigationTabType } from "@/components/NavigationBar";
import MapSearch from "@/public/icons/MapSearch";
import HomeFilled from "@/public/icons/HomeFilled";
import EventAvailable from "@/public/icons/EventAvailable";
import Person from "@/public/icons/Person";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigationTabs = [
    {
      id: 0,
      icon: <MapSearch className="h-6!" />,
    },
    {
      id: 1,
      icon: <HomeFilled className="h-6!" />,
    },
    {
      id: 2,
      icon: <EventAvailable className="h-6!" />,
    },
    {
      id: 3,
      icon: <Person />,
    },
  ] as NavigationTabType[];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="fixed bottom-0 left-0 pb-2 z-50">
        <NavigationBar options={navigationTabs} />
      </div>
      {children}
    </>
  );
}
