import type { Metadata } from "next";
import NavigationBar from "@/components/NavigationBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<>
      <NavigationBar />
      {children}
    </>
  );
}
